// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIgRK1TrzgygnadsNHEkabBTbXkXvm3g',
    appId: '1:654342034701:web:34ef7458155cee59ce0c44',
    messagingSenderId: '654342034701',
    projectId: 'notification-schedule-7d533',
    authDomain: 'notification-schedule-7d533.firebaseapp.com',
    storageBucket: 'notification-schedule-7d533.firebasestorage.app',
    measurementId: 'G-KCB9E0HK54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7veHdM-VDRp3HdHKEpnzrvgswYQw0N8',
    appId: '1:654342034701:android:6fc5ceed792f704fce0c44',
    messagingSenderId: '654342034701',
    projectId: 'notification-schedule-7d533',
    storageBucket: 'notification-schedule-7d533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6grprcX2-RMh08Bm3fPoboqcnILaMdG0',
    appId: '1:654342034701:ios:972020d91c5fc831ce0c44',
    messagingSenderId: '654342034701',
    projectId: 'notification-schedule-7d533',
    storageBucket: 'notification-schedule-7d533.firebasestorage.app',
    iosBundleId: 'com.example.notificationSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6grprcX2-RMh08Bm3fPoboqcnILaMdG0',
    appId: '1:654342034701:ios:972020d91c5fc831ce0c44',
    messagingSenderId: '654342034701',
    projectId: 'notification-schedule-7d533',
    storageBucket: 'notification-schedule-7d533.firebasestorage.app',
    iosBundleId: 'com.example.notificationSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjIgRK1TrzgygnadsNHEkabBTbXkXvm3g',
    appId: '1:654342034701:web:c0d16c4af3e4520cce0c44',
    messagingSenderId: '654342034701',
    projectId: 'notification-schedule-7d533',
    authDomain: 'notification-schedule-7d533.firebaseapp.com',
    storageBucket: 'notification-schedule-7d533.firebasestorage.app',
    measurementId: 'G-1G08B2G34V',
  );
}
